from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle
)


def add_section_title(story, title, styles):
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"<b>{title}</b>", styles["Heading2"]))
    story.append(Spacer(1, 6))


def add_table(story, data):
    table = Table(data, colWidths=[170, 300])

    table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ])
    )

    story.append(table)


def generate_pdf(report_data, output_path):
    """
    Generates a professional security report.
    """

    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(output_path)

    story = []

    story.append(
        Paragraph(
            "<b><font size=20>URL Security Analyzer Report</font></b>",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 15))

    story.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 15))

    # -----------------------------------------------------
    # URL
    # -----------------------------------------------------

    add_section_title(
        story,
        "Submitted URL",
        styles
    )

    story.append(
        Paragraph(
            report_data["url"],
            styles["BodyText"]
        )
    )

    # -----------------------------------------------------
    # Overall Result
    # -----------------------------------------------------

    add_section_title(
        story,
        "Overall Security",
        styles
    )

    add_table(story, [

        ["Risk Score", f'{report_data["risk_score"]}%'],

        ["Verdict", report_data["verdict"]]

    ])

    # -----------------------------------------------------
    # Security Checks
    # -----------------------------------------------------

    add_section_title(
        story,
        "Security Checks",
        styles
    )

    add_table(story, [

        ["HTTPS", report_data["https_status"]],

        ["IP Address", report_data["ip_status"]],

        ["Keywords Found", str(report_data["keyword_count"])],

        ["URL Length", str(report_data["url_length"])],

        ["Subdomains", str(report_data["subdomain_count"])],

        ["@ Symbol", report_data["at_status"]],

        ["URL Shortener", report_data["shortener_status"]],

        ["Hyphens", str(report_data["hyphen_count"])],

        ["Domain Age", report_data["domain_age"]],

        ["TLD", report_data["tld_status"]]

    ])

    # -----------------------------------------------------
    # WHOIS
    # -----------------------------------------------------

    add_section_title(
        story,
        "WHOIS Information",
        styles
    )

    whois = report_data["whois"]

    add_table(story, [

        ["Registrar", whois["registrar"]],

        ["Created", whois["creation_date"]],

        ["Updated", whois["updated_date"]],

        ["Expires", whois["expiration_date"]],

        ["Name Servers", whois["name_servers"]]

    ])

    # -----------------------------------------------------
    # SSL
    # -----------------------------------------------------

    add_section_title(
        story,
        "SSL Certificate",
        styles
    )

    ssl = report_data["ssl"]

    add_table(story, [

        ["Issuer", ssl["issuer"]],

        ["Valid From", ssl["valid_from"]],

        ["Valid Until", ssl["valid_to"]],

        ["Days Remaining", str(ssl["days_remaining"])],

        ["Status", ssl["status"]]

    ])

    # -----------------------------------------------------
    # DNS
    # -----------------------------------------------------

    add_section_title(
        story,
        "DNS Records",
        styles
    )

    dns = report_data["dns"]

    dns_rows = []

    for record_type, values in dns.items():

        value = ", ".join(values) if values else "None"

        dns_rows.append([record_type, value])

    add_table(story, dns_rows)

    # -----------------------------------------------------

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Generated by URL Security Analyzer</b>",
            styles["Heading3"]
        )
    )

    doc.build(story)